---
- name: Restart tinc
  service:
    name: "{{ tinc_service }}"
    state: restarted
  become: yes

- name: Reload tinc
  service:
    name: "{{ tinc_service }}"
    state: reloaded
  become: yes
...
